Feature/#24 implement image management modules
higuruchi/injesh pull request #26
Opened 2022-03-01 07:04 UTC by higuruchi

Close: #24 

# 内容

- rootfsイメージを管理するImage構造体と、関連するモジュールを実装した

2022-03-01 07:49 UTC, yassi-github commented on src/image.rs
> +        let distri_and_version: Vec<&str> = image.split("/").collect();
validationがほしい
splitって失敗したらpanicした気がする

2022-03-01 08:20 UTC, yassi-github commented on src/image.rs
> +            if meta.time().compare(&newest_time) == 1 {
compareの返り値をenumとかにしないなら，コメントでどういう条件文なのかを明記してほしい(数値はわからん)

2022-03-01 08:25 UTC, yassi-github commented on src/image.rs
> +            self.version()
この関数内で`self.user().images(),self.distri ... `がめっちゃ使われているので，あらかじめformatしたStringかなんかを変数に束縛しておいて，その変数を引数に使うとよいかと

2022-03-01 08:27 UTC, yassi-github commented on src/image.rs
> +            self.version()
関数を超えて，Image構造体のメソッドで共通して使われているので
いっそ構造体のメンバに加えてもいいかも？

2022-03-03 06:00 UTC, yassi-github requested changes

2022-03-03 06:00 UTC, yassi-github commented on src/image.rs
> +    /// let image = image::Image::new("ubuntu/focal", user);
コメントもアプデしといて～

2022-03-03 06:00 UTC, yassi-github commented on src/image.rs
> +    }
これ，`~/.injesh/images/distri/version/`の有無を確認してるだけなので，
そのpath以下にあるアーカイブファイル(rootfs.tar.xz)またはアーカイブファイル展開後のrootfsディレクトリの有無を確認するとよさそう

2022-03-03 06:00 UTC, yassi-github commented on src/image.rs
> +        println!("rootfs: {:?}", self.rootfs_hash_path());
ここでrootfsのpathをprintしちゃうのはまずそう

2022-03-03 06:00 UTC, yassi-github commented on src/image_downloader_lxd.rs
> +    fn check_rootfs_newest(&self, to: &Path) -> Result<bool, Box<dyn std::error::Error>> {
`to`(や`from`)という変数は何を表しているかわかりづらいので，
`local_rootfs_hash_path`のようにしたらいいと思いますた

2022-03-03 06:00 UTC, yassi-github commented on src/image.rs
> +            self.version()
`image_base_path`で置換できそう
この下のコードも，`image_base_path/ROOTFS`と表せる

2022-03-03 06:00 UTC, yassi-github commented on src/image_downloader_lxd.rs
> +    }
引数の`distribution`, `version`, `arch`，使わないならいらなくね

2022-03-03 06:00 UTC, yassi-github commented on src/image_downloader_lxd.rs
> +    }
すぐ下の`download_rootfs_hash`も同じく

2022-03-03 06:00 UTC, yassi-github commented on src/image.rs
> +            self.version()
というか，
ここの関数，`fs::create_dir_all(image_base_path/ROOTFS)`でできる
(rootfsをremoveする必要もないしそれによって再DLする必要もない)

2022-03-03 06:00 UTC, yassi-github commented on src/image.rs
> +    /// 呼び出す必要がある
ならば，この中で，ローカルのrootfsが最新かどうかの検証をすればよい．

`setup_rootfs_directory()`で，
1. `~/.injesh/images/distri/version/rootfs/`まで`create_dir_all`で作成
2. `~/.injesh/images/distri/version/rootfs.tar.xz`の有無を確認
(3.) `~/.injesh/images/distri/version/rootfs.tar.xz.asc`の
    - 有無
    - 最新か否か
    を確認
4. アーカイブファイルが無い (OR 最新でない) ((3.)を行って常にローカルのrootfsを最新のにしていいものかは要検討) だったら，`Ok`(後続のDL処理に続く．他はErrを返す)

というようにしたらどうか

2022-03-03 06:00 UTC, yassi-github commented on src/image_downloader_lxd.rs
> +    /// ]
ユーザーの指定した ディス鳥とバージョン に限定した，`ImageMeta`のベクタなら，
このように書いたほうが正確
```suggestion
    /// # Example
    /// ```ignore
    /// [
    ///     ImageMeta{
    ///         distribution: "ubuntu",
    ///         version: "focal",
    ///         atch: "amd64",
    ///         time: NaviveDateTime,
    ///         path: "/images/ubuntu/focal/arm64/default/20220227_07:43/",
    ///     },
    ///     ImageMeta{
    ///         distribution: "ubuntu",
    ///         version: "focal",
    ///         atch: "amd64",
    ///         time: NaviveDateTime,
    ///         path: "/images/ubuntu/focal/amd64/default/20220227_20:34/",
    ///     },
    /// ]
```

2022-03-03 06:00 UTC, yassi-github commented on src/test_image.rs
> +}
test用のファイルにするなら，
`src/test_*.rs`でなく，`tests/*.rs`にしたほうがいいんじゃない
https://doc.rust-jp.rs/book-ja/ch11-03-test-organization.html#%E7%B5%90%E5%90%88%E3%83%86%E3%82%B9%E3%83%88

2022-03-03 06:16 UTC, higuruchi commented on src/test_image.rs
> +}
lib.rsでpubにしてないものに関してもtests以下のディレクトリでアクセスできるの？

2022-03-03 07:03 UTC, yassi-github commented on src/test_image.rs
> +}
できなかった

でもsrc以下にテスト用にファイル分けるのは違和感なので，`image.rs`(`image.*`メソッドをテストしているので)あたりでやってほしい気持ち

2022-03-03 07:54 UTC, higuruchi commented on src/test_image.rs
> +}
image.rs内でテストを行おうとすると、image_downloader_lxd.rsにも依存が生じてしまう。
image.rsはimage_downloader.rsの依存のみにしたい。そのため、テストを行うファイルを分離してる

2022-03-03 08:02 UTC, higuruchi commented on src/image.rs
> +    }
`rootfs.tar.xz`は展開した後、削除しているので、`~/.injesh/images/distri/version/rootfs/`を確認するよう修正します

2022-03-03 08:31 UTC, yassi-github commented on src/test_image.rs
> +}
テストであっても依存関係は絶対なのか～なら仕方ないか...
ならせめて，`src/tests/*`みたいにできない？できなかったらこのままでいいけど

2022-03-03 08:32 UTC, yassi-github commented on src/image.rs
> +    }
`~/.injesh/images/distri/version/rootfs/`もどうです
このディレクトリが一番重要なので

2022-03-03 08:37 UTC, higuruchi commented on src/test_image.rs
> +}
そうすると、無駄なところにpubをつけんといかんくなるが、、、
テストしやすくするためい設計を変更するならともかく(振る舞いは変わらない)、テストのために振る舞いをを変更するのはどうなのだろうと思ってしまう

2022-03-03 08:41 UTC, yassi-github commented on src/test_image.rs
> +}
> そうすると、無駄なところにpubをつけんといかんくなる

ならそのままがいいな

2022-03-03 10:31 UTC, higuruchi commented on src/image.rs
> +    }
rootfsディレクトリは`setup_rootfs_directory`モジュールで作られるから。
作った後、rootfsのアーカイブのダウンロードが失敗した場合もrootfsディレクトリは存在することになる。

そのため、rootfsディレクトリをチェックするのはイメージがあることへの補償としては弱いと感じたから

2022-03-03 10:37 UTC, yassi-github requested changes

2022-03-03 10:37 UTC, yassi-github commented on src/image.rs
> +        }
ディレクトリがない，or バージョンが古い(のはこの関数を呼び出す前に確認しているが，誤って確認を逃し，最新版であっても消してしまうことを防ぐ意味でも，この関数に入れたほうが便利では？) なら強制的に(再)DLするということで
また，実際にDLするときに rootfs ディレクトリが作成されるため，ここでは作らないようにする

```suggestion
        fs::create_dir_all(self.image_base_path())?

        // rootfs があるなら古いバージョンと見做して消去する
        if Path::new(&self.rootfs_path()).exists() {
            fs::remove_dir_all(&self.rootfs_path())?;
        }
```

2022-03-03 10:37 UTC, yassi-github commented on src/image_downloader_lxd.rs
> +    fn download_rootfs(&self, to: &Path) -> Result<(), Box<dyn std::error::Error>> {
欲を言えばここと…

```suggestion
    fn download_rootfs(&self, destination: &Path) -> Result<(), Box<dyn std::error::Error>> {
```

2022-03-03 10:37 UTC, yassi-github commented on src/image_downloader_lxd.rs
> +    fn download_rootfs_hash(&self, to: &Path) -> Result<(), Box<dyn std::error::Error>> {
ここも…

```suggestion
    fn download_rootfs_hash(&self, destination: &Path) -> Result<(), Box<dyn std::error::Error>> {
```

2022-03-03 10:52 UTC, yassi-github commented on src/image.rs
> +    }
rootfsの有無を確認する目的なら，
```rust
if fs::read_dir("~/.injesh/images/distri/version/rootfs")?.count() == 0 {
    /* there is no files under rootfs dir */
}
```
のようにするのが単純で確実と思った

2022-03-03 11:08 UTC, higuruchi commented on src/image.rs
> +        }
> 実際にDLするときに rootfs ディレクトリが作成されるため

というのはアーカイブをダウンロードして展開した時ということ？

2022-03-03 11:17 UTC, yassi-github commented on src/image.rs
> +        }
そう
https://github.com/higuruchi/injesh/pull/26/files#diff-9e8d03b9988bc5a6f26a988a9d956e3dbaf95ea6d9c9eb55676c311f76b32140R187
ここで作られると思っている

もしかして作られない？
なら，elseを加えて，rootfsがないときはディレクトリを作成する
とする？

2022-03-03 11:20 UTC, higuruchi commented on src/image.rs
> +        }
作られないです

2022-03-03 11:22 UTC, yassi-github commented on src/image.rs
> +        }
りょ

2022-03-03 11:28 UTC, higuruchi commented on src/image.rs
> +        }
create_dir_allは便利そうなので利用します。

2022-03-03 12:09 UTC, yassi-github commented on src/image.rs
> +        }
コメントあるからめっちゃわかるんだけど，コード読むと引っかかるので:
```suggestion
        // rootfsディレクトリがある場合は最新ではないのでrootfsディレクトリ以下を削除する
        // ないならば作る
        if Path::new(&self.rootfs_path()).exists() {
            fs::remove_dir_all(&self.rootfs_path())?;
        } else {
            fs::create_dir_all(&self.rootfs_path())?;
        }
```

2022-03-03 12:16 UTC, yassi-github approved these changes

2022-03-03 12:17 UTC, merged