Feature/#7 implement launch
higuruchi/injesh pull request #43
Opened 2022-03-18 06:33 UTC by higuruchi

# 内容

launchコマンドを実装

## デモ

```bash
$ sudo ./target/debug/injesh  launch <Contaioner ID>  --rootfs-image ubuntu/focal <DContainer_Name> /bin/bash
cmd"/bin/bash"
root@aef30e90a84b:/# ls
bin  boot  dev  etc  home  lib  lib32  lib64  libx32  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
root@aef30e90a84b:/# 
```

## 実装状況

- [ ] --rootfs=/path/to/rootfs
- [x] --rootfs-image=<image-name>
- [ ] --rootfs-docker=<docker-container-id>
- [ ] --rootfs-lxd=<lxd-container-name>

## 不具合

- container.rsのreloadメソッドが #36 に実装されているため、これをmergeしてから修正する
- user namespaceをsetnsすると失敗する
- `sudo ./target/debug/injesh  launch ae  --rootfs-image ubuntu/focal hoge ls`をすると失敗する
- `sudo ./target/debug/injesh  launch ae  --rootfs-image ubuntu/focal hoge bash`は成功する

2022-03-18 06:51 UTC, yassi-github commented
コードなんも読んでないが、不具合についてとりあえず:
- user namespaceをsetnsすると失敗する
  - `nsenter`コマンドの`--all`オプションでは、`user` namespace のsetnsは[行っていない](https://github.com/higuruchi/injesh/blob/134c5746af21ec0296989a4eee7c32b87458780a/src/cmd/exec.rs#L174)のでする必要はないかと。
- `ls`が失敗して`bash`が成功する
  - 謎……コード読んでみます

2022-03-18 06:53 UTC, higuruchi commented
container.rs周りのコンフリクトを修正

2022-03-18 12:11 UTC, yassi-github requested changes
レビュー前/後で実行してみたがENOENTになる

```
root@tashkent:/home/ys/injesh# ./target/debug/injesh launch b97c1a8271c9 --rootfs-image alpine/3.15 hoge bash
cmd: "bash"
execute launch command error: ENOENT
Child exited Exited(Pid(90065), 0)
root@tashkent:/home/ys/injesh# rm -rf ~/.injesh/containers/hoge/
root@tashkent:/home/ys/injesh# ./target/debug/injesh launch b97c1a8271c9 --rootfs-image alpine/3.15 hoge ls
cmd: "ls"
execute launch command error: ENOENT
Child exited Exited(Pid(90540), 0)
```

2022-03-18 12:11 UTC, yassi-github commented on src/parser.rs
> +
~~振る舞いは変わっていないので変更する必要はないかと~~

2022-03-18 12:11 UTC, yassi-github commented on src/parser.rs
> +    Launch::new(container, rootfs, String::from(launch.name), launch.cmd)
`Ok`で包んでやるほうがわかりやすいと思った。

```suggestion
    Ok(Launch::new(container, rootfs, String::from(launch.name), launch.cmd)?)
```

2022-03-18 12:11 UTC, yassi-github commented on src/image_downloader_lxd.rs
> +            }
```suggestion
            Err(_) => {
                return Ok(false);
            }
```

2022-03-18 12:11 UTC, yassi-github commented on src/cmd/launch.rs
> +    /// /var/lib/docker/overlay2/<CONTAINER_ID>/upperを~/.injesh/containers/<hoge>/upperに対してコピーする
正確には、overlay2のpathはcontainer_idではない

2022-03-18 12:11 UTC, yassi-github commented on src/cmd/launch.rs
> +                    Err(_) => return Err(Error::Waitpid)?,
```suggestion
                    Err(_) => Err(Error::Waitpid)?,
```

2022-03-18 12:11 UTC, yassi-github commented on src/cmd/launch.rs
> +                    println!("cmd{:?}", cmd);
```suggestion
                    // For Debug
                    // println!("cmd: {:?}", cmd);
```

2022-03-18 12:11 UTC, yassi-github commented on src/cmd/launch.rs
> +                Err(_) => return Err(Error::Fork)?,
```suggestion
                Err(_) => Err(Error::Fork)?,
```

2022-03-18 12:11 UTC, yassi-github commented on src/cmd/launch.rs
> +    }
重複している部分を解消

setting.yaml -> settings.yaml

```suggestion
) -> Result<(), Box<dyn std::error::Error>> {
    // rootfsの種類などが記載された設定ファイルsettings.yamlを~/.injesh/containers/に作成する
    let launch_container_path = format!("{}/{}", launch.user().containers(), launch.name());
    let launch_container_path = std::path::Path::new(&launch_container_path);
    if launch_container_path.exists() {
        Err(Error::AlreadyExists)?
    } else {
        fs::create_dir_all(launch_container_path.join("upper"))?;
        let mut setting_file = fs::File::create(launch_container_path.join("settings.yaml"))?;
        // TODO: 設定ファイルの形式を決める
        setting_file.write_all(b"content of settings.yaml")?;
    }
```

2022-03-18 12:11 UTC, yassi-github commented on src/cmd/launch.rs
> +    for entry in fs::read_dir(launch.target_container().upperdir())? {
この実装では、1階層のみのファイルしかコピーできないので、再帰的にディレクトリを含めてコピーするようにしたい

2022-03-18 12:11 UTC, yassi-github commented on src/cmd/launch.rs
> +        }
```suggestion
            match image.check_rootfs_newest() {
                Ok(is_newest) => if !is_newest {
                    image.download_image()?;
                },
                Err(e) => {
                    Err(e)?
                }
            }
            image.rootfs_path()
        }
```

2022-03-18 12:11 UTC, yassi-github commented on src/cmd/launch.rs
> +        _ => return Err(Error::NotImplemented)?,
```suggestion
        _ => Err(Error::NotImplemented)?,
```

2022-03-18 12:11 UTC, yassi-github commented on src/cmd/launch.rs
> +        .ok_or(Error::WorkDirNotFound)?;
https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.to_str
Fails if path is invalid unicode
なのでNotFoundエラーでなく、NonValidUnicodeエラーあたりにしておくのがいいんではないだろうか。

2022-03-18 12:11 UTC, yassi-github commented on src/cmd/launch.rs
> +        })
基となるpathを定義しておく
openは&strでいけるっぽいので、わざわざpathにしなくていいかな…？

```suggestion
        let ns_base_path = format!("/proc/{}/ns", container_pid);
        Ok(Ns {
            net: File::open(format!("{}/net", &ns_base_path))?,
            cgroup: File::open(format!("{}/cgroup", &ns_base_path))?,
            ipc: File::open(format!("{}/ipc", &ns_base_path))?,
            pid: File::open(format!("{}/pid", &ns_base_path))?,
            user: File::open(format!("{}/user", &ns_base_path))?,
            mnt: File::open(format!("{}/mnt", &ns_base_path))?,
            uts: File::open(format!("{}/uts", &ns_base_path))?,
        })
```

2022-03-19 03:01 UTC, yassi-github commented
エラーになるのはforkしてる部分なので、
launchはマウントし直してrestartするまでにして、実行部分はexecコマンドにまかせてくれればよいかと。(内部でexecコマンド叩くか、実装内容をコピーするか、共通化するか。)

そしてexecを実行するためには、

- [ ] #44 

を解決する必要がある。

2022-03-19 15:45 UTC, higuruchi commented
僕の方ではforkは問題なく実行できる


> レビュー前/後で実行してみたがENOENTになる
> 
> ```
> root@tashkent:/home/ys/injesh# ./target/debug/injesh launch b97c1a8271c9 --rootfs-image alpine/3.15 hoge bash
> cmd: "bash"
> execute launch command error: ENOENT
> Child exited Exited(Pid(90065), 0)
> root@tashkent:/home/ys/injesh# rm -rf ~/.injesh/containers/hoge/
> root@tashkent:/home/ys/injesh# ./target/debug/injesh launch b97c1a8271c9 --rootfs-image alpine/3.15 hoge ls
> cmd: "ls"
> execute launch command error: ENOENT
> Child exited Exited(Pid(90540), 0)
> ```

`cmd`の部分を`bash`でなく`/bin/bash`にするとできる

2022-03-19 15:58 UTC, higuruchi commented
> エラーになるのはforkしてる部分なので、 launchはマウントし直してrestartするまでにして、実行部分はexecコマンドにまかせてくれればよいかと。(内部でexecコマンド叩くか、実装内容をコピーするか、共通化するか。)
> 
> そしてexecを実行するためには、
> 
> * [ ]  [settings.yamlの書式を決める #44](https://github.com/higuruchi/injesh/issues/44)
> 
> を解決する必要がある。

execする部分はコード量があるわけではないので、execが完成してから考えればいいかな

2022-03-19 16:11 UTC, higuruchi commented
`exec`システムコールを発行する際の引数が間違っていた

$ sudo ./target/debug/injesh  launch 35  --rootfs-image ubuntu/focal <DCONTAINER_NAME> /bin/echo hoge

複数引数にも対応

2022-03-19 23:18 UTC, yassi-github requested changes

2022-03-19 23:18 UTC, yassi-github commented on src/parser.rs
> +
~~ここも変更する必要ないです~~

2022-03-19 23:18 UTC, yassi-github commented on src/command.rs
> +}
構造体の名前が`Command`だと、このモジュールの根幹についてのものかと思ってしまう(が、commandモジュールはinjeshのサブコマンドを扱うモジュールである)。また、`std::command::Command`とダブるので勘違いしやすい。

変数名を読みやすく変更

イテレータの全要素に単純な操作をするなら、for文よりmapのが適切と思う

```suggestion
#[derive(Debug)]
pub struct ExecuteCommand {
    index: usize,
    main: String,
    args: Vec<String>,
}

impl ExecuteCommand {
    pub fn new(raw_commands: Vec<String>) -> ExecuteCommand {
        let mut raw_commands_iter = raw_commands.iter();
        let main = match raw_commands_iter.next() {
            Some(cmd) => cmd.to_string(),
            None => "/bin/bash".to_string(),
        };

        let args: Vec<String> = raw_commands_iter.map(|arg| arg.to_string()).collect();

        ExecuteCommand {
            index: 0,
            main: main,
            args: args,
        }
    }

    pub fn main(&self) -> &str {
        &self.main
    }

    pub fn args(&self) -> &Vec<String> {
        &self.args
    }
}
```

2022-03-19 23:18 UTC, yassi-github commented on src/command.rs
> +}
`index`は何に使う予定なの？

2022-03-19 23:18 UTC, yassi-github commented on src/command.rs
> +        })
`Launch`構造体に`User`を入れる理由？

launch.rsの`initialize_setting`で使っているようだが、`initialize_setting`の中で`User::new()`すればよくない？

2022-03-19 23:18 UTC, yassi-github commented on src/cmd/launch.rs
> +    }
ここupperにディレクトリがあったら失敗するので再帰的にする必要あり

2022-03-19 23:18 UTC, yassi-github commented on src/parser.rs
> +fn initialize_launch<'a>(
ライフタイム演算子使わないなら消しといて〜

2022-03-20 02:34 UTC, yassi-github commented on src/parser.rs
> +
`unwrap_or`でErrの早期リターンはできないっぽい。めっちゃ勘違いしてた。

2022-03-20 02:35 UTC, yassi-github commented on src/parser.rs
> +
`unwrap_or`でErrの早期リターンはできないっぽい。めっちゃ勘違いしてた。

2022-03-21 02:56 UTC, yassi-github requested changes

2022-03-21 02:56 UTC, yassi-github commented on src/command.rs
> +        };
`parser::LaunchArgs`のcmdメンバは`Vec<String>`なので、
それをそのままnew()の引数に渡し、new()の中でiterに変換すればBoxなど使わなくて済むのでは？

2022-03-21 02:56 UTC, yassi-github commented on src/command.rs
> +        };
また、`String.to_string()`になっているのを解消する

```suggestion
impl Cmd {
    pub fn new(mut detail: Box<dyn Iterator<Item = String>>) -> Cmd {
        let main = match detail.next() {
            Some(cmd) => cmd,
            None => "/bin/bash".to_string(),
        };
```

2022-03-21 02:56 UTC, yassi-github commented on src/command.rs
> +        Box::new(self.detail.iter().map(|string| (*string).as_str()))
vecの中身を&strにしたイテレータを返しているだけやんね？
各処理で簡単にできるだろうし、cmdのメソッドにするメリットが見受けられないので、なくしていいと思う。

2022-03-21 02:56 UTC, yassi-github commented on src/cmd/launch.rs
> +    Ok(1)
- 繰り返し内で絶対に変わらない値を初期化するのを解消するためforの外に出した
- 一旦 &str にしてからPathに変換しているようだが、[DirEntryはPathBufに直接変更できる](https://doc.rust-lang.org/std/fs/struct.DirEntry.html#method.path)ので、Pathにそろえてから`join`でつなげてやって簡潔にした
- u64が返っても仕事しないので、返り値の型を`Ok(())`に変更した

```suggestion
fn copy_dir_recursively<P, Q>(from: P, to: Q) -> Result<(), Box<dyn std::error::Error>>
where
    P: AsRef<OsStr> + AsRef<Path>,
    Q: AsRef<OsStr> + AsRef<Path>,
{
    if !Path::new(&from).is_dir() {
        Err(Error::InputValue)?
    }
    if !Path::new(&to).is_dir() {
        Err(Error::InputValue)?
    }

    let to_name = Path::new(&to).to_str().ok_or(Error::InputValue)?;
    for entry_result in fs::read_dir(from)? {
        let entry = entry_result?;

        let to_path = Path::new(to_name).join(entry.path().file_name().ok_or(Error::InputValue)?);
        
        if entry.file_type()?.is_dir() {
            fs::create_dir(&to_path)?;
            copy_dir_recursively(entry.path(), &to_path)?;
        } else {
            fs::copy(entry.path(), &to_path)?;
        }
    }

    Ok(())
```

2022-03-21 02:56 UTC, yassi-github commented on src/cmd/launch.rs
> +            fs::create_dir_all(format!("{}/upper", &dcontainer_base))?;
- boolで分岐するならmatchではなく if文を使う
- Errの早期リターンするなら `return` でなく `?` を使う
    - releted review: https://github.com/higuruchi/injesh/pull/43/files#r829899132

```suggestion
    if Path::new(&dcontainer_base).exists() {
        Err(Error::AlreadyExists)?
    } else {
        fs::create_dir_all(format!("{}/upper", &dcontainer_base))?;
```

2022-03-21 02:56 UTC, yassi-github commented on src/cmd/launch.rs
> +                        .collect();
mapだけではエラーハンドリングが難しいので、`filter_map`あたりを使うとよさげに思う

このようにすると`command::Cmd`の`detail_iter`メソッドを除去可能

```suggestion
                    let detail: Vec<CString> = launch
                        .cmd()
                        .detail()
                        .iter()
                        .filter_map(|s| CString::new(s.as_str()).ok())
                        .collect::<Vec<CString>>();
```

2022-03-21 07:32 UTC, yassi-github approved these changes

2022-03-21 07:35 UTC, merged