Bug/#53 fix delete fail
higuruchi/injesh pull request #58
Opened 2022-03-28 08:35 UTC by yassi-github

2022-03-30 05:02 UTC, higuruchi requested changes

2022-03-30 05:02 UTC, higuruchi commented on src/cmd/delete.rs
> +}
launch.rs内にも同じ関数があるため、util.rsにまとめた方がいい？

2022-03-30 05:02 UTC, higuruchi commented on src/container.rs
> +    pub fn convert_injesh_name_to_docker_id(
デバック対象コンテナの呼び名をb`デバックコンテナ`か`injeshコンテナ`どちらに統一する？

2022-04-07 08:27 UTC, yassi-github commented on src/container.rs
> +    pub fn convert_injesh_name_to_docker_id(
`debug_container`でどうでしょ
`convert_debug_container_name_to_docker_id`みたいになりそう

2022-04-07 08:29 UTC, yassi-github commented on src/cmd/delete.rs
> +}
#54

2022-07-12 18:15 UTC, yassi-github commented
確認した。
みつかった問題点はissue #54 , #59 に上げてるのであとで直すとして、
とりまマージでおｋかと思われ :saluting_face:

2022-07-13 04:04 UTC, merged